baseurl = "https://codelog.netflfy.com"
title = "CodeLog"
author = "SeongAh Jo"
paginate = 5
theme = "hpstr"

[params]
    description = "A minimal Hugo theme"
    replaceGoogleFonts = "fonts.loli.net"
    twitter = "example"
    facebook = "example"
